#cloud-config
write_files:
 - content: |
    AllowUsers ${loginUser}
    PasswordAuthentication no
    PermitRootLogin no
    ChallengeResponseAuthentication no
    UsePAM yes
   path: /etc/ssh/sshd_config.d/restrict-ssh.conf
   permissions: '0644'
users:
 - name: ${loginUser}
   groups: sudo
   shell: /bin/bash
   sudo: ALL=(ALL) NOPASSWD:ALL
   ssh_authorized_keys:
    - ${public_key_deniz}
    - ${public_key_nico}
    - ${public_key_goik}
packages:
  - nginx
runcmd:
  - systemctl enable nginx
  - rm /var/www/html/*
  - >
    echo "I'm Nginx @ $(dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com) 
    created $(date -u)" >> /var/www/html/index.html
  - systemctl restart ssh